### ISSUE TITLE
improve transys documentation (both API doc and tutorial) 

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#89]
I spent almost an hour to figure out how to create a transition system in `TuLiP` and then gradually add attributes (and I still don't know how, so I'm giving up on it). I'm not sure if this is because the functionality does not exist or if it is there but not well-documented. I think `transys` now heavily uses `networkX`. For `TuLiP` users who are not particularly familiar with `networkX`, it would be useful to include pointers to relevant parts of `networkX` documentation (at the bare minimum, `"Wraps L{LabeledDiGraph.add_node}"` to `"Wraps C{networkx.MultiDiGraph.add_node}"`). 

Here is what I want to do:
* Create an `FTS` with `N` states and atomic propositions `'a', 'b', 'c'`.
* Add label `'a'` to a subset `S1` of states, then add label `'b'` to the subset `S2` of states, and label `'c'` to the subset `S3` of states. Note that `S1`, `S2` and `S3` are not necessarily disjoint.

I know how to first form the set of labels for each state and then add the label set to a state but I would like to be able to do it gradually add labels.

Does `networkX` provide an easy way of implementing the above simple procedure (I couldn't find a direct way)? If not, does `TuLiP` provide a simple way of implementing this?

**Comment by slivingston** [comment]
@johnyf: will you have a chance to address this in the next 2 days? If not, I could take a shot.

**Comment by johnyf** [comment]
I can try to address this, so that it can be closed.

**Comment by johnyf** [comment]
I mention [above](https://github.com/tulip-control/tulip-control/issues/89#issuecomment-43394904) that I would have liked `networkx` to allow defining your own custom `dict` class for storing node and edge attributes. This feature has since been made available by the `networkx` developers. A description for how such `dict` factories can be defined in a subclass can be found [in the docstring of `networkx.DiGraph`](https://github.com/networkx/networkx/blob/fdbf0ef15d4c5be0f695fc1b9a660082b7c95219/networkx/classes/digraph.py#L167).

This facility obviates my hacking of `networkx.MultiDiGraph` to implant `TypedDict`. This would be an improvement. An overriding improvement would be to replace `transys` with a simpler implementation, like the one in `omega.automata`. Most of `transys` can be erased w/o losing essential functionality, as done in a sequence of commits starting with [791f94517dde07ef4097a71b730744fba087df8e](https://github.com/johnyf/tulip-control/commit/791f94517dde07ef4097a71b730744fba087df8e). This is a side-comment, clearly such a change would require extensive changes throughout, and I don't suggest that `omega.automata` will remain stable.

**Comment by slivingston** [comment]
The remaining action item to close this issue is, quoting [from above](https://github.com/tulip-control/tulip-control/issues/89#issuecomment-47289842), "...to transfer part of the discussion here into the docstrings, and write a (short) tutorial on using LabeledDiGraph and its subclasses."

@johnyf: I will attempt to do this if you have not. Please advise by re-assigning the issue to me if appropriate.

**Comment by johnyf** [comment]
I have been working on a draft for the tutorial that I will push to a branch while working on it, so that others can read it, while I continue.

**Comment by johnyf** [comment]
In the tutorial, I am avoiding reference to inside-out methods like `LabeledDiGraph.states.add`.
Instead, I directly use `LabeledDiGraph.add_node`.
This is flat (and not misleading, as the nested `states.add` is), (almost) identical with `networkx`, and will change the least with any simplifying changes we may decide to apply in the future.

It also makes redundant [lengthy explanations](https://github.com/tulip-control/tulip-control/issues/89#issuecomment-43457648) that attempt to remedy confusion.

**Comment by johnyf** [comment]
The memory concerns [mentioned above](https://github.com/tulip-control/tulip-control/issues/89#issuecomment-43458064) are premature optimization. For a problem of size that causes memory issues, one would either use Cython, or C, or implement a custom class, or use symbolic algorithms directly.

**Comment by slivingston** [comment]
Done as of 6b07c3189f2a5a9b9e775aa2179c821b6b7ad5e3. Relevant changes are on master branch as of 50e6262834d3973b387b60650eeb83f3c3f8a116.
